### ISSUE TITLE
Initial version

### ISSUE THREAD

**Issue by patricksavalle** [mobbr/mobbr-plugin-firefox#1]
Same functionality as the Chrome plugin. See repo description.

If you start working on this issue, please notify us in the comments.

**Comment by bartleijssenaar** [comment]
This issue is taken.

**Comment by davidsemakula** [comment]
@patricksavalle  Checkout https://github.com/mobbr/mobbr-plugin-firefox/pull/2

**Comment by patricksavalle** [comment]
Cool :) It works!

I will figure out how to upload this to the Firefox repository.
